### ISSUE TITLE
conv_psf doubling due to FourierTools package

### ISSUE THREAD

**Issue by renerichter** [roflmaostc/DeconvOptim.jl#17]
If I run: 

```
using Revise # for development useful
using DeconvOptim, TestImages, Colors, FFTW, Noise, ImageShow
#
img = Float32.(testimage("resolution_test_512"))
psf = Float32.(generate_psf(size(img), 30))
img_b = conv_psf(img, psf)
```
The warning " WARNING: both FourierTools and DeconvOptim export "conv_psf"; uses of it in module workspace9 must be qualified" is generated and conv_psf is not calculated. Maybe changing the nomenclature between the packages could cause troubles in far (or near) future?

**Comment by roflmaostc** [comment]
Thanks for pointing that out.

We probably deprecated all related `conv` methods in DeconvOptim.jl and try to use the one of FourierTools.

You can fix by using `DeconvOptim.conv_psf` or `FourierTools.conv_psf`, they are the same basically.
However, in DeconvOptim we sometimes change the memory allocation etc.

**Comment by renerichter** [comment]
Thanks for the fast reaction. 
I think deprecating conv-methods in DeconvOptim gives a further improvement of clear package- and usage-separation. Looking forward to having conv_psf in FourierTools only somewhen. :)
