### ISSUE TITLE
Misleading `generate_psf` function

### ISSUE THREAD

**Issue by kunzaatko** [roflmaostc/DeconvOptim.jl#44]
`generate_psf` gives a `fftshift`ed PSF instead of what is expected. If this will be hard to fix if intended so, since
I think that it is passed this way throughout the whole package, meaning that everywhere, where the PSF is `fft`ed, the
output is expected to be non-`fftshift`ed.

An alternative would be to point this out in the documentation, but this does make it non-intuitive for using PSFs
generated through a model or another package since they would have to be `fftshifted`, before passed to the

**Comment by roflmaostc** [comment]
Can you specify what exactly is misleading?

I agree, that `generate_psf` could be not exported but it also does not hurt much.
For more advanced PSFs see
https://github.com/RainerHeintzmann/PointSpreadFunctions.jl

**Comment by roflmaostc** [comment]
Ah you edited it :smile: 

Yes, `DeconvOptim.jl` expects all PSFs to be centered around `(1,1,1)` (btw, I would call this `ifftshifted`). Back then I liked that convention more than having the center in the middle.

I'm a little afraid to change it since it would imply big changes everywhere

**Comment by roflmaostc** [comment]
Do you want to prepare a PR to maybe add some clarification here?

https://github.com/roflmaostc/DeconvOptim.jl/blob/4c30146df86c28ebcc0cd017eeba7bea9b71d27f/src/deconvolution.jl#L6

and here?

 https://github.com/roflmaostc/DeconvOptim.jl/blob/4c30146df86c28ebcc0cd017eeba7bea9b71d27f/src/utils.jl#L254

**Comment by kunzaatko** [comment]
> For more advanced PSFs see
> https://github.com/RainerHeintzmann/PointSpreadFunctions.jl
I didn't know about this! I am in the process of creating my own package... Will look into this one, though. I created a repo for it now, so you can take a look if you want to: https://github.com/kunzaatko/TransferFunctions.jl

**Comment by roflmaostc** [comment]
Ah!
Tagging @RainerHeintzmann that he's aware of your package too

**Comment by kunzaatko** [comment]
Oh, my... Now I see that the code was formatted. Sorry for that... Should I undo that?

**Comment by roflmaostc** [comment]
Maybe add the tabs to the function arguments back. Otherwise they are fine.
Tests currently fail because of a test dependency. Fix it later.

Thanks!

**Comment by RainerHeintzmann** [comment]
Sure. Lets talk in August.
